[package]
org = "ballerina"
name = "data.jsondata"
version = "1.1.1"
authors = ["Ballerina"]
keywords = ["json", "json path", "json-transform", "json transform", "json to json", "json-convert", "json convert"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.jsondata"
license = ["Apache-2.0"]
distribution = "2201.12.0"
export = ["data.jsondata"]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "jsondata-native"
version = "1.1.1"
path = "../native/build/libs/data.jsondata-native-1.1.1-SNAPSHOT.jar"

[[platform.java21.dependency]]
path = "./lib/json-path-2.9.0.jar"
groupId = "com.jayway.jsonpath"
artifactId = "json-path"
version = "2.9.0"

[[platform.java21.dependency]]
path = "./lib/json-smart-2.4.11.jar"
groupId = "net.minidev.json"
artifactId = "json-smart"
version = "2.4.11"

[[platform.java21.dependency]]
path = "./lib/accessors-smart-2.4.7.jar"
groupId = "net.minidev.json"
artifactId = "accessors-smart"
version = "2.4.7"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.7.0"
path = "./lib/constraint-native-1.7.0.jar"
