[plugin]
id = "constraint-compiler-plugin"
class = "io.ballerina.lib.data.jsondata.compiler.JsondataCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/data.jsondata-compiler-plugin-1.0.0-SNAPSHOT.jar"
